### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by yellowjaguar5** [vibber/CefWithSyphon#8]
Hello!
I just downloaded the latest version and I think I cannot scroll on any page. Any ideas?

**Comment by vibber** [comment]
Hi Benjamin,
I am sorry but you have encountered a limitation of this software which is
a very experimental thing I adapted from an existing package. I basically
just added syphon capability to an existing browser demo. In other words I
don't know how to modify it to get this working.
I would recommend trying some of the screen capturing software out there.
Have a look on the official syphon page for options.
http://syphon.v002.info

**Comment by yellowjaguar5** [comment]
Okay. Thanks for the quick response.
